
/*
 * Copyright (c) 2020. University of Canterbury
 *
 * This file is part of SENG301 lab material.
 *
 *  The lab material is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The lab material is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this material.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package gradle.cucumber.asg1.service;
import org.junit.Test;

import uc.seng301.asg1.service.RecipeService;

import static org.junit.Assert.*;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.junit.BeforeClass;

import java.util.List;

public class RecipeServiceTest {

    private static SessionFactory factory;
    private static RecipeService service;
    private static RecipeService service1;

    @BeforeClass
    public static void init() {
        // see test/resource file that is using an embedded H2 database (see https://www.h2database.com/html/main.html)
        // with this h2 database, you are not using the sqlite file and therefore can create self-contained tests
        // you can simply create a test-dedicated environment by putting test resources under the test folder
        Configuration configuration = new Configuration();
        configuration.configure();
        factory = configuration.buildSessionFactory();
        service = new RecipeService(factory);
        service1 = new RecipeService(factory);
    }


    /**
     * Test to check it does not add recipes that are not in valid format
     */
    @Test
    public void testAddInvalidRecipe() {
        String name = "tiramisu123";
        int result = service.addRecipe(name);
        assertEquals(result, -1);
    }

    /**
     * Test to check it returns all recipe ids wit the same recipe name
     */
    @Test
    public void testGetRecipeIdsByName() {
        String name = "chicken pho";
        String name1 = "chicken pho";
        service1.addRecipe(name);
        service1.addRecipe(name1);
        List<Short> recipeIds = service1.getRecipeIdsByName("chicken pho");
        int result = recipeIds.get(0);
        int result2 = recipeIds.get(1);

        assertEquals(recipeIds.size(), 2);
        assertEquals(result, 1);
        assertEquals(result2, 2);
    }
}
